sonar.projectKey=tax.ngitung.com
sonar.projectName=Calculate Tax
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
sonar.exclusions=node_modules/**
