import type {
  Activity,
  Deadline,
  DonutSegment,
  MgmtMenu,
  MonthlyData,
  NavItem,
  Setoran,
  StatCard,
  TaxTarget,
  WajibPajak,
} from "@common/types/mockdata.type";

// ─── NAV ITEMS ───────────────────────────────────────────────
export const navItems: NavItem[] = [
  // Utama
  {key: "dashboard", label: "Dashboard", icon: "🏠", section: "Utama"},
  {key: "kalkulator", label: "Kalkulator Pajak", icon: "🧮", section: "Utama"},
  {key: "laporan", label: "Laporan & Analitik", icon: "📊", section: "Utama"},
  // Manajemen
  {
    key: "wajibpajak",
    label: "Wajib Pajak",
    icon: "👤",
    badge: 248,
    badgeColor: "danger",
    section: "Manajemen",
  },
  {key: "badan", label: "Badan Usaha", icon: "🏢", section: "Manajemen"},
  {
    key: "spt",
    label: "SPT & Formulir",
    icon: "📁",
    badge: 12,
    badgeColor: "success",
    section: "Manajemen",
  },
  {key: "setoran", label: "Setoran Pajak", icon: "💳", section: "Manajemen"},
  {
    key: "buktipotong",
    label: "Bukti Potong",
    icon: "📑",
    badge: 5,
    badgeColor: "warning",
    section: "Manajemen",
  },
  {key: "arsip", label: "Arsip Dokumen", icon: "🗂️", section: "Manajemen"},
  // Keuangan
  {key: "realisasi", label: "Realisasi Pajak", icon: "📈", section: "Keuangan"},
  {
    key: "jatuhtempoNav",
    label: "Jatuh Tempo",
    icon: "🔔",
    badge: 3,
    badgeColor: "danger",
    section: "Keuangan",
  },
  {key: "rekap", label: "Rekap SSP / BPHTB", icon: "🏦", section: "Keuangan"},
  // Sistem
  {key: "pengguna", label: "Pengguna & Akses", icon: "👥", section: "Sistem"},
  {key: "pengaturan", label: "Pengaturan", icon: "⚙️", section: "Sistem"},
  {key: "log", label: "Log Aktivitas", icon: "📋", section: "Sistem"},
];

// ─── STAT CARDS ──────────────────────────────────────────────
export const statCards: StatCard[] = [
  {
    id: "1",
    label: "Total Penerimaan Pajak",
    value: "Rp 4,7 M",
    sub: "dari bulan lalu",
    trend: "up",
    trendValue: "12.4%",
    icon: "💰",
    gradient: "indigo",
  },
  {
    id: "2",
    label: "Wajib Pajak Aktif",
    value: "2.481",
    sub: "pendaftar baru",
    trend: "up",
    trendValue: "38",
    icon: "👥",
    gradient: "rose",
  },
  {
    id: "3",
    label: "SPT Dilapor Bulan Ini",
    value: "1.204",
    sub: "kepatuhan",
    trend: "down",
    trendValue: "48.5%",
    icon: "✅",
    gradient: "sky",
  },
  {
    id: "4",
    label: "Jatuh Tempo Bulan Ini",
    value: "3",
    sub: "Terdekat: 20 Feb",
    trend: "neutral",
    trendValue: "",
    icon: "⏰",
    gradient: "amber",
  },
];

// ─── MANAGEMENT MENUS ────────────────────────────────────────
export const mgmtMenus: MgmtMenu[] = [
  {
    id: "wp",
    icon: "👤",
    label: "Wajib Pajak",
    count: "2.481 data",
    iconBg: "bg-primary-100",
    borderColor: "hover:border-primary",
  },
  {
    id: "spt",
    icon: "📁",
    label: "Manaj. SPT",
    count: "1.204 laporan",
    iconBg: "bg-danger-100",
    borderColor: "hover:border-danger",
  },
  {
    id: "set",
    icon: "💳",
    label: "Setoran",
    count: "Rp 4,7 M total",
    iconBg: "bg-success-100",
    borderColor: "hover:border-success",
  },
  {
    id: "bp",
    icon: "📑",
    label: "Bukti Potong",
    count: "348 dokumen",
    iconBg: "bg-warning-100",
    borderColor: "hover:border-warning",
  },
  {
    id: "badan",
    icon: "🏢",
    label: "Badan Usaha",
    count: "127 entitas",
    iconBg: "bg-secondary-100",
    borderColor: "hover:border-secondary",
  },
  {
    id: "arsip",
    icon: "🗂️",
    label: "Arsip",
    count: "4.800+ file",
    iconBg: "bg-success-50",
    borderColor: "hover:border-success",
  },
];

// ─── WAJIB PAJAK (Table) ─────────────────────────────────────
export const wajibPajakData: WajibPajak[] = [
  {
    id: "1",
    name: "Budi Santoso",
    npwp: "78.234.567.8-012.000",
    category: "OP",
    company: "PT Teknologi Nusantara",
    grossIncome: 15000000,
    ptkp: "K/1",
    taxDue: 1462500,
    status: "Lunas",
    period: "Jan 2025",
    avatarColor: "bg-gradient-indigo",
    registeredAt: "2025-01-05",
  },
  {
    id: "2",
    name: "Sari Rahayu",
    npwp: "12.876.543.2-045.000",
    category: "PN",
    company: "PT Maju Jaya Tbk",
    grossIncome: 22000000,
    ptkp: "K/2",
    taxDue: 2750000,
    status: "Proses",
    period: "Jan 2025",
    avatarColor: "bg-gradient-rose",
    registeredAt: "2025-01-08",
  },
  {
    id: "3",
    name: "Dwi Handayani",
    npwp: "55.123.456.7-033.000",
    category: "OP",
    company: "CV Berkah Mandiri",
    grossIncome: 8500000,
    ptkp: "TK/0",
    taxDue: 237500,
    status: "Belum",
    period: "Jan 2025",
    avatarColor: "bg-gradient-amber",
    registeredAt: "2025-01-10",
  },
  {
    id: "4",
    name: "Rina Permata",
    npwp: "33.445.566.7-011.000",
    category: "PN",
    company: "PT Sentosa Digital",
    grossIncome: 18500000,
    ptkp: "K/0",
    taxDue: 1875000,
    status: "Lunas",
    period: "Jan 2025",
    avatarColor: "bg-gradient-sky",
    registeredAt: "2025-01-12",
  },
  {
    id: "5",
    name: "Ahmad Wahyudi",
    npwp: "98.765.432.1-077.000",
    category: "OP",
    company: "PT Garuda Infrastruktur",
    grossIncome: 35000000,
    ptkp: "K/3",
    taxDue: 6562500,
    status: "Lunas",
    period: "Jan 2025",
    avatarColor: "bg-gradient-violet",
    registeredAt: "2025-01-14",
  },
  {
    id: "6",
    name: "PT Maju Jaya Tbk",
    npwp: "01.234.567.8-999.000",
    category: "Badan",
    company: "Holding Group",
    grossIncome: 500000000,
    ptkp: "K/0",
    taxDue: 75000000,
    status: "Proses",
    period: "Jan 2025",
    avatarColor: "bg-gradient-emerald",
    registeredAt: "2025-01-15",
  },
  {
    id: "7",
    name: "Teguh Prasetyo",
    npwp: "44.556.677.8-022.000",
    category: "OP",
    company: "Freelance",
    grossIncome: 12000000,
    ptkp: "TK/1",
    taxDue: 750000,
    status: "Belum",
    period: "Jan 2025",
    avatarColor: "bg-gradient-rose",
    registeredAt: "2025-01-18",
  },
];

// ─── MONTHLY CHART DATA ──────────────────────────────────────
export const monthlyData: MonthlyData[] = [
  {month: "Jan", pph21: 320, pphBadan: 210},
  {month: "Feb", pph21: 450, pphBadan: 290},
  {month: "Mar", pph21: 380, pphBadan: 250},
  {month: "Apr", pph21: 520, pphBadan: 360},
  {month: "Mei", pph21: 460, pphBadan: 310},
  {month: "Jun", pph21: 590, pphBadan: 420},
  {month: "Jul", pph21: 430, pphBadan: 280},
  {month: "Agu", pph21: 500, pphBadan: 340},
  {month: "Sep", pph21: 650, pphBadan: 460},
  {month: "Okt", pph21: 570, pphBadan: 390},
  {month: "Nov", pph21: 720, pphBadan: 510},
  {month: "Des", pph21: 800, pphBadan: 560},
];

// ─── DONUT DATA ──────────────────────────────────────────────
export const donutData: DonutSegment[] = [
  {
    label: "Tepat Waktu",
    count: 1289,
    pct: 52,
    color: "#10B981",
    chipColor: "success",
  },
  {
    label: "Terlambat",
    count: 694,
    pct: 28,
    color: "#F59E0B",
    chipColor: "warning",
  },
  {
    label: "Belum Lapor",
    count: 498,
    pct: 20,
    color: "#EF4444",
    chipColor: "danger",
  },
];

// ─── DEADLINES ───────────────────────────────────────────────
export const deadlines: Deadline[] = [
  {
    id: "1",
    day: 20,
    month: "Feb",
    title: "SPT Masa PPh 21",
    sub: "Masa Januari 2025",
    urgency: "kritis",
  },
  {
    id: "2",
    day: 28,
    month: "Feb",
    title: "SPT Masa PPN",
    sub: "Masa Januari 2025",
    urgency: "segera",
  },
  {
    id: "3",
    day: 31,
    month: "Mar",
    title: "SPT Tahunan OP",
    sub: "Tahun Pajak 2024",
    urgency: "normal",
  },
  {
    id: "4",
    day: 30,
    month: "Apr",
    title: "SPT Tahunan Badan",
    sub: "Tahun Pajak 2024",
    urgency: "normal",
  },
];

// ─── AKTIVITAS ───────────────────────────────────────────────
export const activities: Activity[] = [
  {
    id: "1",
    icon: "✅",
    iconBg: "bg-success-100",
    text: "SPT Tahunan <b>Budi Santoso</b> berhasil dikirim",
    actor: "Andi Saputra",
    timeAgo: "2 menit lalu",
  },
  {
    id: "2",
    icon: "👤",
    iconBg: "bg-primary-100",
    text: "WP baru <b>PT Maju Jaya Tbk</b> terdaftar",
    actor: "Sistem",
    timeAgo: "15 menit lalu",
  },
  {
    id: "3",
    icon: "💳",
    iconBg: "bg-warning-100",
    text: "Setoran pajak <b>Rp 4.250.000</b> dikonfirmasi",
    actor: "Rina Permata",
    timeAgo: "1 jam lalu",
  },
  {
    id: "4",
    icon: "⚠️",
    iconBg: "bg-danger-100",
    text: "<b>5 WP</b> mendekati jatuh tempo SPT",
    actor: "Auto-notifikasi",
    timeAgo: "3 jam lalu",
  },
  {
    id: "5",
    icon: "📑",
    iconBg: "bg-secondary-100",
    text: "Bukti potong <b>1721-A1</b> dicetak batch (32 lembar)",
    actor: "Andi Saputra",
    timeAgo: "5 jam lalu",
  },
];

// ─── SETORAN ─────────────────────────────────────────────────
export const setoranData: Setoran[] = [
  {
    id: "1",
    wpName: "Budi Santoso",
    type: "PPh 21",
    amount: 1462500,
    sspNo: "2025021401",
    date: "Hari ini, 09:15",
    color: "bg-gradient-indigo",
  },
  {
    id: "2",
    wpName: "PT Garuda Infra",
    type: "PPh Badan",
    amount: 6562500,
    sspNo: "2025021402",
    date: "Hari ini, 11:42",
    color: "bg-gradient-rose",
  },
  {
    id: "3",
    wpName: "Rina Permata",
    type: "PPh 21",
    amount: 1875000,
    sspNo: "2025021301",
    date: "Kemarin, 14:30",
    color: "bg-gradient-sky",
  },
  {
    id: "4",
    wpName: "CV Berkah Mandiri",
    type: "PPh 23",
    amount: 450000,
    sspNo: "2025021302",
    date: "Kemarin, 16:00",
    color: "bg-gradient-amber",
  },
];

// ─── TAX TARGETS ─────────────────────────────────────────────
export const taxTargets: TaxTarget[] = [
  {
    id: "1",
    label: "PPh 21 Karyawan",
    realized: 2400,
    target: 4000,
    color: "bg-gradient-indigo",
    textColor: "text-primary",
  },
  {
    id: "2",
    label: "PPh Badan",
    realized: 1100,
    target: 1500,
    color: "bg-gradient-rose",
    textColor: "text-danger",
  },
  {
    id: "3",
    label: "PPN",
    realized: 900,
    target: 1800,
    color: "bg-gradient-sky",
    textColor: "text-success",
  },
  {
    id: "4",
    label: "PPh Pasal 23/26",
    realized: 300,
    target: 400,
    color: "bg-gradient-amber",
    textColor: "text-warning",
  },
];
